### ISSUE TITLE
Create New Page for Liked Products

### ISSUE THREAD

**Issue by vineet1202** [Niharika0104/TrendTrove#102]
**Is your feature request related to a problem? Please describe.**
Currently, the application lacks a dedicated route for users to see the products they have liked. Implementing a favorites route will enhance user experience by providing easy access to their preferred items without navigating through the entire product catalog.

**Describe the solution you'd like**
1. Backend Implementation:

  Introduce a new endpoint /favorites in our backend API.
  Implement logic to retrieve liked products for the current user from the database.
  Ensure the endpoint returns a JSON response containing relevant product information (e.g., ID, name, image URL, price).

2. Frontend Integration:

  Create a new route /favorites in our frontend application that triggers a request to the backend /favorites endpoint.
  Display the list of liked products in a user-friendly manner, such as a grid or list view.
  Each product should include at least basic information (name, image, price) and a link to view more details.
  
I would like to work on this feature under SSOC.

**Comment by Kritika30032002** [comment]
same as wishlist feature
