### ISSUE TITLE
Add Shimmer UI for Product Loading

### ISSUE THREAD

**Issue by 0xaira** [Niharika0104/TrendTrove#106]
### Description
To enhance the user experience on our eCommerce platform, I propose adding a Shimmer UI effect while the products are loading. This will provide a more engaging visual feedback to users, indicating that the content is being loaded, and improve the perceived performance of the site.

### Details

- **Feature:** Shimmer UI for product loading
- **Pages affected:** All pages where product data is fetched and displayed
- **Scope:** This feature will involve creating a Shimmer UI component and integrating it into the existing product listing and product detail pages.

### My Proposed Solution
1. Create a reusable Shimmer UI component.
2. Integrate the Shimmer UI component in the product listing page.
3. Integrate the Shimmer UI component in the product detail page.
4. Ensure the Shimmer effect is visible until the product data is fully loaded.
5. Test the Shimmer UI on various devices and screen sizes for responsiveness.

**Comment by Kritika30032002** [comment]
duplicate #104
