### ISSUE TITLE
Open Graph Implementation - Change from default to custom

### ISSUE THREAD

**Issue by Trident09** [Niharika0104/TrendTrove#11]
### **Feature Request: Add Open Graph Support**

**Feature missing.**

Currently, links from this website don't display rich previews on social media, making shared content look unattractive.

**Describe the solution you'd like**

Add Open Graph tags to our website, including:

- `og:title`
- `og:description`
- `og:image`
- `og:url`

This will ensure our links generate engaging previews on social media.

**Alternatives considered**

Considered using Twitter Card tags, but Open Graph tags are more universally supported across various platforms.

Adding these tags will improve the appearance of our shared content.

**Comment by Niharika0104** [comment]
@Trident09 go ahead! Thanks for bringing this up.
