### ISSUE TITLE
Favicon not present 

### ISSUE THREAD

**Issue by Trident09** [Niharika0104/TrendTrove#13]
### Add Favicons to Website

I'm always frustrated when I can't easily identify our website in my browser tabs because it lacks a favicon.

**Describe the solution you'd like**
Add a favicon to the website to make it easily recognizable in browser tabs and bookmarks.

Please assign this issue to me under SSOC

**Comment by Niharika0104** [comment]
@Trident09  Someone already fixed this issue.
