### ISSUE TITLE
Rearrange Homepage Layout

### ISSUE THREAD

**Issue by Trident09** [Niharika0104/TrendTrove#15]
### Rearrange Homepage Layout

**Is your feature request related to a problem? Please describe.**
The homepage layout could be more user-friendly. Currently, the "Premium Quality," "Secure Payment," and "Express Shipping" sections are above the product categories, making it less intuitive for users to find and browse products.

**Describe the solution you'd like**
Rearrange the homepage layout so that the product categories are displayed above the "Premium Quality," "Secure Payment," and "Express Shipping" sections.

**Describe alternatives you've considered**
N/A

**Additional context**
Current layout screenshot:
![Current Layout](https://i.imgur.com/i6VwMYR.jpeg)

**Comment by Niharika0104** [comment]
@Trident09 I don't see any problem with those being above products.

**Comment by Trident09** [comment]
I think those are secondary details, the products should be the center of attraction in a e-commerce website 

that's why I brought up this issue. Its okay if you think the current layout is okay
