### ISSUE TITLE
The default selection for product wishlist should be un-wishlisted

### ISSUE THREAD

**Issue by kushagra-singhh** [Niharika0104/TrendTrove#16]
**Describe the bug**
The default selection of item is wishlisted.

**Expected behavior**
The default selection of a product being wishlisted or not should be set to un-wishlisted ( hollow heart 😔 )

**Screenshots**
![Screenshot_2024-06-07-17-16-26-417_com android chrome](https://github.com/Niharika0104/TrendTrove/assets/88451512/9fe853bd-f5c8-4044-8a37-7c43acb49e6d)

**Comment by kushagra-singhh** [comment]
Please assign me this issue under SSOC.

**Comment by Niharika0104** [comment]
@kushagra-singhh Make sure that it should be a button and they should toggle between void and fill.
