### ISSUE TITLE
Add Wishlist Feature and fix Main logo size

### ISSUE THREAD

**Issue by Akash4701** [Niharika0104/TrendTrove#18]
**Is your feature request related to a problem? Please describe.**

Add a new wishlist feature to the website. Users should be able to add items to their wishlist, view the wishlist, and remove items from the wishlist. The wishlist should be stored in localStorage to persist across sessions.

**Describe the solution you'd like**

1.Create a React Context to manage the wishlist state globally.
2.Implement functions to add and remove items from the wishlist and store these changes in localStorage.
3.Create a Wishlist component to display the wishlist items.
4.Update existing components to include the option to add items to the wishlist.
5.Ensure the wishlist state persists across sessions using localStorage.

Acceptance Criteria:

Users can add items to the wishlist.
Users can view their wishlist items.
Users can remove items from the wishlist.
The wishlist state is saved in localStorage and persists across sessions.
The implementation is responsive and works on various devices and browsers.

**Comment by Akash4701** [comment]
PLease assign me this issue @Niharika0104 for SSoC'2024

**Comment by Niharika0104** [comment]
@Akash470 .Front end is there for this feature just integrate it with backend.Tell me your approach for this.How are you going to change the schema for this.

**Comment by nandita27iitp** [comment]
@Kritika30032002 Can I work on it

**Comment by Kritika30032002** [comment]
add #5 in this only as that is very small change
