### ISSUE TITLE
Modification in search bar

### ISSUE THREAD

**Issue by mandalriddhi** [Niharika0104/TrendTrove#33]
**Describe the bug**
Search bar is not working. A few modifications are needed.

**To Reproduce**
1. Go to code
2. Click on part that contain the search bar
3. Scroll down to that specific part
4. Discover the errors and debug it

**Expected behavior**
Now the search bar is not working. If I want to search anything from the links that are given in the front page of the of the website are all ok, but when I try to search something using the search bar that is not working. Finally I want to search something using the search bar ,if that is available in the website then it will be shown, otherwise the result will come not found.

**Additional context**
I am SSOC'24 contributor.
Please assign me this issue.

**Comment by Niharika0104** [comment]
@mandalriddhi I want that when u search for sarees just redirect the users to sarees page and so on with whatever products that has been mentioned that is what you said as well just to make sure that we are on same page on this feature implementation.

**Comment by mandalriddhi** [comment]
yes

**Comment by mandalriddhi** [comment]
Yes I actually want to implement it
