### ISSUE TITLE
Enhancing navbar

### ISSUE THREAD

**Issue by harikasayani** [Niharika0104/TrendTrove#37]
**Is your feature request related to a problem? Please describe.**
I observed that navbar is not looking good.

**Describe the solution you'd like**
I want to add more features to it to make attractive.
I'll add some CSS properties and icons to it to looks attractive.

**Additional context**
I am SSOC'24 Contributor.
Please assign me this task.

**Comment by Niharika0104** [comment]
@harikasayani There are other issues that are fixing this.
