### ISSUE TITLE
Change the styling of the page and add footer to it.

### ISSUE THREAD

**Issue by shivani-negi** [Niharika0104/TrendTrove#38]
**Is your feature request related to a problem? Please describe.**
I observed that styling of the website is not looking good and there is no footer.

**Describe the solution you'd like**
I want to style the home page of the website
I'll add some CSS ,bootstrap properties and make the hover effect on the image to it to looks attractive.
I also want to make footer of the website.

**Additional context**
I am SSOC'24 Contributor.
Please assign me this task.

**Comment by Niharika0104** [comment]
@shivani-negi Other people opened the issues which are fixing this issue.

**Comment by Niharika0104** [comment]
Just comment there I will assign it to you.

**Comment by shivani-negi** [comment]
@Niharika0104 ok assign this task to me
