### ISSUE TITLE
Changing the styling of the header section and adding next button to the front page image 

### ISSUE THREAD

**Issue by AnantAgarwaL11** [Niharika0104/TrendTrove#39]
**Is your feature request related to a problem? Please describe.**

Adding profile , Wishlist name below its symbol so that the user don't face any difficulty and adding next button in the main image button so that it will look more attractive

**Additional context**

I am SSOC'24 Contributor.
Please assign me this task.

**Comment by Kritika30032002** [comment]
@AnantAgarwaL11  Please brief more about your issue
