### ISSUE TITLE
Dark/light mode button

### ISSUE THREAD

**Issue by Soumyacode1-prog** [Niharika0104/TrendTrove#43]
Implementing a dark and light mode toggle is a straightforward way to enhance the user experience, accessibility, and visual appeal of your application. By allowing users to switch between modes, you cater to different preferences and usage contexts, making your application more versatile and user-friendly.

PLEASE ALLOW ME TO MAKE THESE CHANGES.
THANKYOU!

**Comment by Niharika0104** [comment]
Duplicate issues
