### ISSUE TITLE
Photos are stretched out.

### ISSUE THREAD

**Issue by Arnav-Saxena** [Niharika0104/TrendTrove#44]
### Photos on this website are stretched to fit instead of filled in, hence , they look slimmed down or stretched out.   
**This can be fixed by some changes in the website's css.**  
      
**I would like to fix this issue.**
                
![Screenshot 2024-06-07 234037](https://github.com/Niharika0104/TrendTrove/assets/169916884/88c97fff-072d-42c5-9d58-391c669035dc)

![Screenshot 2024-06-07 234045](https://github.com/Niharika0104/TrendTrove/assets/169916884/25b432f5-55dd-463d-b740-ddf7785d6a9b)

**Comment by mryashsinghal** [comment]
I want to work on this issue please assign this to me

**Comment by Rajneesh2223** [comment]
Can I work on this issue as there is no response from the assigned side
