### ISSUE TITLE
Feature🌟 : Add "Scroll to Top" Button 

### ISSUE THREAD

**Issue by aslams2020** [Niharika0104/TrendTrove#45]
Hi @Niharika0104 ,
here is the issue i encountered -

**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to scroll back to the top of a long page manually. 
This can be time-consuming and inconvenient for users, especially on pages with extensive content.

## Screenshot 
- This is where we should add the feature 
![image](https://github.com/Niharika0104/TrendTrove/assets/131389695/940e0c77-7edc-4606-a361-3c0826730ecd)

**Describe the solution you'd like**

I would like to implement a "Scroll to Top" button that appears when the user scrolls down the page.
This button should be prominently displayed and easy to click, allowing users to quickly return to the top of the page with a single click. The button can be styled to fit the design of the website and could be positioned at the bottom right corner of the viewport.

@Niharika0104, Could you please assign me this issue under SSOC'24 ?

**Comment by Niharika0104** [comment]
Duplicate #34
