### ISSUE TITLE
[Enhancement] Landing page UI should be updated

### ISSUE THREAD

**Issue by mdkaifansari04** [Niharika0104/TrendTrove#48]
**Describe the bug**
Currently, all the cards and sections are not aligned with their parent hence making a bad user experience and the design should be changed. 

Following elements design can be updated :
- Navbar
- Searchbar
- Crousel 
- Featured section
- Category section
- Product Card

**To Reproduce**
1. Navigate to the home route or visit - https://trend-trove-client-side.vercel.app/

**Screenshots**
-Navbar
![image](https://github.com/Niharika0104/TrendTrove/assets/117475603/f37e2633-b8a2-4d76-83fb-f68a9bfb62b3)

- Crousel
![image](https://github.com/Niharika0104/TrendTrove/assets/117475603/cf9da360-7a54-4113-a56b-b532806164f4)

- Featured section
![image](https://github.com/Niharika0104/TrendTrove/assets/117475603/dd93f9b8-75c6-4d26-b16e-b1b7d16721df)

- Category section
![image](https://github.com/Niharika0104/TrendTrove/assets/117475603/ab0f6184-d509-4e6e-9ad2-a2789ef85e05)

- Product card
![image](https://github.com/Niharika0104/TrendTrove/assets/117475603/bee6fcb2-754a-4f2b-8e4e-4701a0eff662)

**Comment by Niharika0104** [comment]
@mdkaifansari04 sure make it look appealing and better than current design
