### ISSUE TITLE
[BUG] Product Search Bar is not working

### ISSUE THREAD

**Issue by mdkaifansari04** [Niharika0104/TrendTrove#49]
**Describe the bug**
The product search bar is not functioning correctly, preventing users from finding products.

**To Reproduce**
1. Go to the homepage or any page with the search bar.
2. Enter a product name or keyword in the search bar.
3. Click the search button or press Enter.
4. Observe that no results are returned or incorrect results are displayed.

**Expected behavior**
The search bar should filter and display relevant products based on the entered keyword.

**Screenshots**
![image](https://github.com/Niharika0104/TrendTrove/assets/117475603/6e6def59-7565-45fe-a85d-4f30996fee8c)
**Additional context**
I am SSOC'24 Contributor.

**Comment by captainsahil001** [comment]
i want to work on this issue @mdkaifansari04 @Niharika0104

**Comment by Kritika30032002** [comment]
@mdkaifansari04  You are already assigned with a lot of issues that's why I am assigning this to @captainsahil001 .  
@mdkaifansari04 Try to complete the already assigned issues as soon as possible.

**Comment by mdkaifansari04** [comment]
Yeah, I was busy with some other work and although I'll try to complete it as soon as possible

**Comment by Kritika30032002** [comment]
@mdkaifansari04  You can un assign yourself from some issues if you think you will be unable to complete them
