### ISSUE TITLE
[Feature Request]: User Authentication API

### ISSUE THREAD

**Issue by mdkaifansari04** [Niharika0104/TrendTrove#52]
**Describe the bug**
The application currently lacks a secure user authentication system.

**To Reproduce**
1. Attempt to register or log in to the application.
2. Observe the absence of a secure authentication process.
3. Notice the lack of password recovery options and session management.

**Expected behavior**
Implement a user authentication system allowing users to securely register, log in, and log out. Include password recovery options and session management.

**Additional context**
I am SSOC'24 Contributor.

**Comment by Rajneesh2223** [comment]
Can I work on this issue

**Comment by Rajneesh2223** [comment]
here is the demo of it

https://github.com/Niharika0104/TrendTrove/assets/127289297/50aa6e7b-bac3-4f0b-8f5b-cbed694c181e
