### ISSUE TITLE
[BUG]: Uncertain Code and Folder Structure

### ISSUE THREAD

**Issue by mdkaifansari04** [Niharika0104/TrendTrove#54]
## Describe the bug
The code and folder structure are messy, causing confusion. It's hard to maintain and debug.

## To Reproduce

Go to the project repository.
1. Open the code and folder structure.
2. Try to locate specific files or understand the organization.
3. See the disorganization.

## Expected behavior
A clear and consistent structure to make maintenance and debugging easier.

## Additional context
I am SSOC'24 Contributor.

**Comment by mdkaifansari04** [comment]
Hey, I have updated the folder structure and ready to create the PR.

We should consider this first

**Comment by Niharika0104** [comment]
@mdkaifansari04 Let the folder structure be as it is right now.You can organize the public folder in the client folder if you want. Do let me know on this.

**Comment by mdkaifansari04** [comment]
I have structured all the component based on their use case 

Here is the screenshot of it 
![image](https://github.com/Niharika0104/TrendTrove/assets/117475603/2e842a22-6ed6-4e5c-9d4c-9ac74f04eaa4)

**Comment by mdkaifansari04** [comment]
I only have structured the client folder not the server one and also have removed some unused codes. It's completely fine and wanted to push it first and then work on further issues
