### ISSUE TITLE
[UI Enhancement] : Login Page Redesign

### ISSUE THREAD

**Issue by mdkaifansari04** [Niharika0104/TrendTrove#58]
**Describe the bug**
The login page needs improvement for better user experience. The fields and buttons are not clearly defined.

**To Reproduce**
1. Go to the login page.
2. Observe the current design and layout.
3. Try to identify the username/email and password fields and the login button.
4. Notice the lack of clarity and emphasis.

**Expected behavior**
Simplify the login page. Clearly define the fields for username/email and password, and highlight the "Login" button.

**Screenshots**
![image](https://github.com/Niharika0104/TrendTrove/assets/117475603/6c223fef-e0b2-4793-baa7-8eecf99432ae)

**Additional context**
I am SSOC'24 Contributor.

**Comment by HemantKr071** [comment]
I would like to work on the issue if no one is working on it.
Please assign me this issue.
