### ISSUE TITLE
[Feature Request]: Registration Functionality

### ISSUE THREAD

**Issue by mdkaifansari04** [Niharika0104/TrendTrove#59]
**Describe the bug**
There is no dedicated registration page for new users to sign up.

**To Reproduce**
1. Go to the application.
2. Look for a sign-up or registration option.
3. Notice the absence of a dedicated registration page.
4. See the inability for new users to create an account.

**Expected behavior**
Create a registration page where new users can enter their details to sign up for an account.

**Screenshots**
![image](https://github.com/Niharika0104/TrendTrove/assets/117475603/61f40d41-0d0c-4559-a02c-e6ea91a0ab04)

**Additional context**
I am SSOC'24 Contributor.

**Comment by Kritika30032002** [comment]
@Niharika0104

**Comment by Kritika30032002** [comment]
duplicate #26
