### ISSUE TITLE
I want to fix the first face of this Project

### ISSUE THREAD

**Issue by RS-labhub** [Niharika0104/TrendTrove#6]
![image](https://github.com/Niharika0104/TrendTrove/assets/117426013/22be9ef6-3788-4fa7-a4f7-f4cc42a58c82)

The face must cover up the like this only:
![image](https://github.com/Niharika0104/TrendTrove/assets/117426013/790f6ae1-c3f0-4680-94d8-6ee14eea2b79)

(UI improvemet)

SSOC

**Comment by Niharika0104** [comment]
@RS-labhub assigning this issue to you!
