### ISSUE TITLE
[FEAT] Make Product Card CSS More Interactive

### ISSUE THREAD

**Issue by Atanu789** [Niharika0104/TrendTrove#61]
# Feature Request: Interactive Product Card CSS for TrendTrove

**Is your feature request related to a problem? Please describe.**
The current CSS design does not provide any interactive elements or animations, which makes the user experience less dynamic and potentially less appealing.

**Describe the solution you'd like**
I would like to enhance the product card CSS to include interactive elements. This could involve:
- Adding hover effects such as shadow enlargements, slight rotations, or color transitions.
- Implementing animations when a product card is clicked, such as expanding the card to show more details.
- Adding smooth transitions for any changes in the card, making the interaction feel seamless.

**Additional context**
I believe these enhancements will significantly improve the user experience on TrendTrove's website, making it more engaging and visually appealing.

Thank you for considering this feature request!

**Comment by Atanu789** [comment]
hey @Niharika0104 kindly assign me this issue under SSOC'24

**Comment by Kritika30032002** [comment]
@Atanu789  What are the updates?

**Comment by Atanu789** [comment]
I have made changes for the cards. Kindly review it.

https://github.com/Niharika0104/TrendTrove/assets/123866162/23dc33de-ce5d-4474-8af5-3a743bab7c32

**Comment by Kritika30032002** [comment]
@Atanu789 design need improvement

**Comment by Atanu789** [comment]
sure. I will work on that

**Comment by Kritika30032002** [comment]
@Atanu789 Any updates?
