### ISSUE TITLE
 [Feature] Add Category Page

### ISSUE THREAD

**Issue by mdkaifansari04** [Niharika0104/TrendTrove#67]
**Description**
Implement a new category page feature to enhance user navigation and product browsing. This page will display products grouped by their respective categories, making it easier for users to find what they are looking for.

**To Reproduce**
Steps to reproduce the absence of the feature:
1. Navigate to the home page.
2. Look for category-based navigation.
3. Notice that there is no dedicated category page to view products by category.

**Expected behavior**
A category page that displays products grouped by their respective categories, with filters and sorting options for better user experience.

**Screenshots**
If applicable, add screenshots to help explain your request.

**Additional context**
I am SSOC'24 Contributor.

**Comment by Niharika0104** [comment]
There is already category based routing in the home page.When u click on ethnic wear you will be redirected to page which only displays ethnic wear.🙂
