### ISSUE TITLE
[Feature] Add All Products Page

### ISSUE THREAD

**Issue by mdkaifansari04** [Niharika0104/TrendTrove#68]
**Description**
Implement a new "All Products" page to allow users to view all available products in one place. This page should display a comprehensive list of products with options to filter and sort the results.

**To Reproduce**
Steps to reproduce the absence of the feature:
1. Navigate to the home page.
2. Look for a link or option to view all products.
3. Notice that there is no dedicated page to view all products in one place.

**Expected behavior**
An "All Products" page that lists all available products, with features for filtering and sorting to enhance user navigation and product discovery.

**Screenshots**

**Additional context**
I am SSOC'24 Contributor.

**Comment by Niharika0104** [comment]
That would be messy,I want users to browse products according to the category or search them.
