### ISSUE TITLE
[Feature] Add About Us Page

### ISSUE THREAD

**Issue by mdkaifansari04** [Niharika0104/TrendTrove#70]
**Description**
Implement a new "About Us" page to provide users with information about the company, its mission, values, and team. This page should help build trust and connection with users by sharing the company's story and background.

**To Reproduce**
Steps to reproduce the absence of the feature:
1. Navigate to the website.
2. Look for an "About Us" link in the navigation bar or footer.
3. Notice that there is no dedicated "About Us" page providing company information.

**Expected behavior**
An "About Us" page that includes details about the company's history, mission, values, team members, and any other relevant information. This page should be easily accessible from the navigation bar or footer.

**Screenshots**
If applicable, add screenshots to help explain your request.

**Additional context**
I am SSOC'24 Contributor.

**Comment by Niharika0104** [comment]
I don't want this to be on the website.This should be probably included in the footer itself just like how Myntra has it.
