### ISSUE TITLE
[Feature] Add Contact Us / Request Feature Page

### ISSUE THREAD

**Issue by mdkaifansari04** [Niharika0104/TrendTrove#71]
**Description**
Implement a new "Contact Us" or "Request Feature" page to allow users to get in touch with the company for support, feedback, or feature requests. This page should provide a form for users to fill out their contact information and message.

**To Reproduce**
Steps to reproduce the absence of the feature:
1. Navigate to the website.
2. Look for a "Contact Us" or "Request Feature" link in the navigation bar or footer.
3. Notice that there is no dedicated page for contacting the company or requesting features.

**Expected behavior**
A "Contact Us" or "Request Feature" page with a form where users can enter their name, email, and message. The form should be user-friendly and easy to submit. Additionally, include contact information such as the company's email, phone number, and address if applicable.

**Screenshots**
If applicable, add screenshots to help explain your request.

**Additional context**
I am SSOC'24 Contributor.

**Comment by Niharika0104** [comment]
Request feature page is not needed as we have GitHub and people can create issue here by describing the feature.Someone is already working on contact us form.
