### ISSUE TITLE
[Feature] Add 404 Page Not Found

### ISSUE THREAD

**Issue by mdkaifansari04** [Niharika0104/TrendTrove#72]
**Description**
Implement a new "404 Page Not Found" page to handle cases where users navigate to a non-existent or broken link. This page should inform users that the requested page could not be found and provide options to navigate back to the homepage or other parts of the site.

**To Reproduce**
Steps to reproduce the absence of the feature:
1. Navigate to a non-existent URL on the website.
2. Observe the current behavior when a page is not found.
3. Notice that there is no dedicated 404 page to handle such cases gracefully.

**Expected behavior**
A "404 Page Not Found" page that clearly informs users that the requested page does not exist. This page should include:
- A message indicating that the page could not be found.
- A link to return to the homepage.
- Additional navigation options or links to popular sections of the site.

**Screenshots**
If applicable, add screenshots to help explain your request.

**Additional context**
I am SSOC'24 Contributor.

**Comment by Niharika0104** [comment]
Duplicate issue
