### ISSUE TITLE
Add Sorting Functionality to Products Section

### ISSUE THREAD

**Issue by jeevan10017** [Niharika0104/TrendTrove#81]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when I can't easily find products in a specific order, such as by price or discount. The current products section cannot sort items, making it difficult for users to quickly locate the best deals or compare products based on price.

**Describe the solution you'd like**

I propose adding sorting functionality to the products section, allowing users to sort items in the following ways:
- Price: Sort products in increasing and decreasing order.
- Discount: Sort products in increasing and decreasing order of discount percentage.
This enhancement will improve the user experience by providing more control over how products are displayed and making it easier to find desired items quickly.

**Describe alternatives you've considered**
An alternative could be implementing filtering options for prices and discounts, but sorting provides a more straightforward way for users to organize and view products based on their preferences. Filters can be used in conjunction, but sorting gives immediate clarity in listing products.

**Additional context**
![Screenshot 2024-06-10 103519](https://github.com/Niharika0104/TrendTrove/assets/132948936/97466d37-c7ac-4edd-9eec-980bb1e40e30)

I am excited about possibly contributing to this project as an SSOC Contributor and look forward to your feedback.

**Comment by Kritika30032002** [comment]
same as #80
