### ISSUE TITLE
Styling the product cards 

### ISSUE THREAD

**Issue by payalgupta25** [Niharika0104/TrendTrove#84]
**Is your feature request related to a problem? Please describe.**
The cards on main page of website are very simply styled , no colors no border no styling 

**Describe the solution you'd like**
I would like to add some styling to the cards on main page of the website 

**Describe alternatives you've considered**
I can style the cards so that they look presentable and eye catchy

**Comment by Niharika0104** [comment]
Duplicate issue already fixed
