### ISSUE TITLE
Add rupee symbol in the Card Section

### ISSUE THREAD

**Issue by tumansutradhar** [Niharika0104/TrendTrove#85]
There is no rupee symbol on the cards I want to add the rupee symbol to the cards

**Comment by Kritika30032002** [comment]
@tumansutradhar  Please brief about your issue.

**Comment by tumansutradhar** [comment]
![treadtrove](https://github.com/Niharika0104/TrendTrove/assets/121193864/bee893dd-a7f7-47f4-a2af-19b3782975b4)
i want to add india rupee symbol

**Comment by Kritika30032002** [comment]
@tumansutradhar  Its a very small change. Also do some other changes so that points could be given to you.
Let me know what other changes can be done by you.
