### ISSUE TITLE
I want to add contributors.md file

### ISSUE THREAD

**Issue by RS-labhub** [Niharika0104/TrendTrove#9]
I hope that makes sense

(SSOC)

**Comment by kom-senapati** [comment]
There's no need for a list of contributors, I suppose. We can add a section on the website to indicate that it's open source and display the current contributors.

**Comment by RS-labhub** [comment]
> There's no need for a list of contributors, I suppose. We can add a section on the website to indicate that it's open source and display the current contributors.

That's necessary @kom-senapati
