### ISSUE TITLE
Add hover effects and improve UI

### ISSUE THREAD

**Issue by Sanglap-Halder** [Niharika0104/TrendTrove#97]
**Is your feature request related to a problem? Please describe.**
The UI is not so good and I think there should be hover effects on the cards

**Describe the solution you'd like**
I will improve the UI and add hover effects

**Describe alternatives you've considered**

**Additional context**

**Comment by Sanglap-Halder** [comment]
I want to do this task under SSOC 2024

**Comment by Kritika30032002** [comment]
Duplicate #61
